export const ADD_CHECKING = 'ADD_CHECKING';
export const CHECKING_LOADING = 'CHECKING_LOADING';
export const CHECKING_FAILED = 'CHECKING_FAILED';

export const ADD_SAVINGS = 'ADD_SAVINGS';
export const SAVINGS_LOADING = 'SAVINGS_LOADING';
export const SAVINGS_FAILED = 'SAVINGS_FAILED';

export const ADD_BUSINESS = 'ADD_BUSINESS';
export const BUSINESS_LOADING = 'BUSINESS_LOADING';
export const BUSINESS_FAILED = 'BUSINESS_FAILED';

export const ADD_CD = 'ADD_CD';
export const CD_LOADING = 'CD_LOADING';
export const CD_FAILED = 'CD_FAILED';

export const ADD_IRA = 'ADD_IRA';
export const IRA_LOADING = 'IRA_LOADING';
export const IRA_FAILED = 'IRA_FAILED';

export const ADD_ROTHIRA = 'ADD_ROTHIRA';
export const ROTHIRA_LOADING = 'ROTHIRA_LOADING';
export const ROTHIRA_FAILED = 'ROTHIRA_FAILED';

export const ADD_ROLLOVER = 'ADD_ROLLOVER';
export const ROLLOVER_LOADING = 'ROLLOVER_LOADING';
export const ROLLOVER_FAILED = 'ROLLOVER_FAILED';

export const ADD_CDRATES = 'ADD_CDRATES';
export const CDRATES_LOADING = 'CDRATES_LOADING';
export const CDRATES_FAILED = 'CDRATES_FAILED';
